// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/shareclass/v1/bond.proto (package sunrise.shareclass.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/shareclass/v1/bond.proto.
 */
export const file_sunrise_shareclass_v1_bond: GenFile = /*@__PURE__*/
  fileDesc("CiBzdW5yaXNlL3NoYXJlY2xhc3MvdjEvYm9uZC5wcm90bxIVc3VucmlzZS5zaGFyZWNsYXNzLnYxIn4KDVZhbGlkYXRvckJvbmQSPAoRdmFsaWRhdG9yX2FkZHJlc3MYASABKAlCIdK0LR1jb3Ntb3MuVmFsaWRhdG9yQWRkcmVzc1N0cmluZxIvCgZhbW91bnQYAiABKAsyGS5jb3Ntb3MuYmFzZS52MWJldGExLkNvaW5CBMjeHwAisgEKCVVuYm9uZGluZxIKCgJpZBgBIAEoBBIpCgdhZGRyZXNzGAIgASgJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmcSPQoPY29tcGxldGlvbl90aW1lGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIIyN4fAJDfHwESLwoGYW1vdW50GAQgASgLMhkuY29zbW9zLmJhc2UudjFiZXRhMS5Db2luQgTI3h8AQtABChljb20uc3VucmlzZS5zaGFyZWNsYXNzLnYxQglCb25kUHJvdG9QAVoyZ2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L3NoYXJlY2xhc3MvdHlwZXOiAgNTU1iqAhVTdW5yaXNlLlNoYXJlY2xhc3MuVjHKAhVTdW5yaXNlXFNoYXJlY2xhc3NcVjHiAiFTdW5yaXNlXFNoYXJlY2xhc3NcVjFcR1BCTWV0YWRhdGHqAhdTdW5yaXNlOjpTaGFyZWNsYXNzOjpWMWIGcHJvdG8z", [file_cosmos_base_v1beta1_coin, file_cosmos_proto_cosmos, file_gogoproto_gogo, file_google_protobuf_timestamp]);

/**
 * ValidatorBond
 *
 * @generated from message sunrise.shareclass.v1.ValidatorBond
 */
export type ValidatorBond = Message<"sunrise.shareclass.v1.ValidatorBond"> & {
  /**
   * @generated from field: string validator_address = 1;
   */
  validatorAddress: string;

  /**
   * @generated from field: cosmos.base.v1beta1.Coin amount = 2;
   */
  amount?: Coin;
};

/**
 * Describes the message sunrise.shareclass.v1.ValidatorBond.
 * Use `create(ValidatorBondSchema)` to create a new message.
 */
export const ValidatorBondSchema: GenMessage<ValidatorBond> = /*@__PURE__*/
  messageDesc(file_sunrise_shareclass_v1_bond, 0);

/**
 * Unbonding
 *
 * @generated from message sunrise.shareclass.v1.Unbonding
 */
export type Unbonding = Message<"sunrise.shareclass.v1.Unbonding"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string address = 2;
   */
  address: string;

  /**
   * @generated from field: google.protobuf.Timestamp completion_time = 3;
   */
  completionTime?: Timestamp;

  /**
   * @generated from field: cosmos.base.v1beta1.Coin amount = 4;
   */
  amount?: Coin;
};

/**
 * Describes the message sunrise.shareclass.v1.Unbonding.
 * Use `create(UnbondingSchema)` to create a new message.
 */
export const UnbondingSchema: GenMessage<Unbonding> = /*@__PURE__*/
  messageDesc(file_sunrise_shareclass_v1_bond, 1);

