// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/shareclass/v1/params.proto (package sunrise.shareclass.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/shareclass/v1/params.proto.
 */
export const file_sunrise_shareclass_v1_params: GenFile = /*@__PURE__*/
  fileDesc("CiJzdW5yaXNlL3NoYXJlY2xhc3MvdjEvcGFyYW1zLnByb3RvEhVzdW5yaXNlLnNoYXJlY2xhc3MudjEiaAoGUGFyYW1zEjoKDXJld2FyZF9wZXJpb2QYASABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25CCMjeHwCY3x8BEhwKFGNyZWF0ZV92YWxpZGF0b3JfZ2FzGAIgASgEOgTooB8BQtIBChljb20uc3VucmlzZS5zaGFyZWNsYXNzLnYxQgtQYXJhbXNQcm90b1ABWjJnaXRodWIuY29tL3N1bnJpc2VsYXllci9zdW5yaXNlL3gvc2hhcmVjbGFzcy90eXBlc6ICA1NTWKoCFVN1bnJpc2UuU2hhcmVjbGFzcy5WMcoCFVN1bnJpc2VcU2hhcmVjbGFzc1xWMeICIVN1bnJpc2VcU2hhcmVjbGFzc1xWMVxHUEJNZXRhZGF0YeoCF1N1bnJpc2U6OlNoYXJlY2xhc3M6OlYxYgZwcm90bzM", [file_gogoproto_gogo, file_google_protobuf_duration]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message sunrise.shareclass.v1.Params
 */
export type Params = Message<"sunrise.shareclass.v1.Params"> & {
  /**
   * @generated from field: google.protobuf.Duration reward_period = 1;
   */
  rewardPeriod?: Duration;

  /**
   * @generated from field: uint64 create_validator_gas = 2;
   */
  createValidatorGas: bigint;
};

/**
 * Describes the message sunrise.shareclass.v1.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_sunrise_shareclass_v1_params, 0);

