// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/tokenconverter/v1/tx.proto (package sunrise.tokenconverter.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { Coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_msg_v1_msg } from "../../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Params } from "./params_pb";
import { file_sunrise_tokenconverter_v1_params } from "./params_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/tokenconverter/v1/tx.proto.
 */
export const file_sunrise_tokenconverter_v1_tx: GenFile = /*@__PURE__*/
  fileDesc("CiJzdW5yaXNlL3Rva2VuY29udmVydGVyL3YxL3R4LnByb3RvEhlzdW5yaXNlLnRva2VuY29udmVydGVyLnYxIrIBCg9Nc2dVcGRhdGVQYXJhbXMSKwoJYXV0aG9yaXR5GAEgASgJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmcSNwoGcGFyYW1zGAIgASgLMiEuc3VucmlzZS50b2tlbmNvbnZlcnRlci52MS5QYXJhbXNCBMjeHwA6OYLnsCoJYXV0aG9yaXR5iuewKiZzdW5yaXNlL3Rva2VuY29udmVydGVyL01zZ1VwZGF0ZVBhcmFtcyIZChdNc2dVcGRhdGVQYXJhbXNSZXNwb25zZSKmAQoKTXNnQ29udmVydBIoCgZzZW5kZXIYASABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxI7CgZhbW91bnQYAiABKAlCK8jeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW500rQtCmNvc21vcy5JbnQ6MYLnsCoGc2VuZGVyiuewKiFzdW5yaXNlL3Rva2VuY29udmVydGVyL01zZ0NvbnZlcnQiFAoSTXNnQ29udmVydFJlc3BvbnNlIvoBCgdNc2dTZW5kEi4KDGZyb21fYWRkcmVzcxgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEiwKCnRvX2FkZHJlc3MYAiABKAlCGNK0LRRjb3Ntb3MuQWRkcmVzc1N0cmluZxJbCgZhbW91bnQYAyADKAsyGS5jb3Ntb3MuYmFzZS52MWJldGExLkNvaW5CMMjeHwCq3x8oZ2l0aHViLmNvbS9jb3Ntb3MvY29zbW9zLXNkay90eXBlcy5Db2luczo0guewKgxmcm9tX2FkZHJlc3OK57AqHnN1bnJpc2UvdG9rZW5jb252ZXJ0ZXIvTXNnU2VuZCIRCg9Nc2dTZW5kUmVzcG9uc2UytQIKA01zZxJuCgxVcGRhdGVQYXJhbXMSKi5zdW5yaXNlLnRva2VuY29udmVydGVyLnYxLk1zZ1VwZGF0ZVBhcmFtcxoyLnN1bnJpc2UudG9rZW5jb252ZXJ0ZXIudjEuTXNnVXBkYXRlUGFyYW1zUmVzcG9uc2USXwoHQ29udmVydBIlLnN1bnJpc2UudG9rZW5jb252ZXJ0ZXIudjEuTXNnQ29udmVydBotLnN1bnJpc2UudG9rZW5jb252ZXJ0ZXIudjEuTXNnQ29udmVydFJlc3BvbnNlElYKBFNlbmQSIi5zdW5yaXNlLnRva2VuY29udmVydGVyLnYxLk1zZ1NlbmQaKi5zdW5yaXNlLnRva2VuY29udmVydGVyLnYxLk1zZ1NlbmRSZXNwb25zZRoFgOewKgFC5gEKHWNvbS5zdW5yaXNlLnRva2VuY29udmVydGVyLnYxQgdUeFByb3RvUAFaNmdpdGh1Yi5jb20vc3VucmlzZWxheWVyL3N1bnJpc2UveC90b2tlbmNvbnZlcnRlci90eXBlc6ICA1NUWKoCGVN1bnJpc2UuVG9rZW5jb252ZXJ0ZXIuVjHKAhlTdW5yaXNlXFRva2VuY29udmVydGVyXFYx4gIlU3VucmlzZVxUb2tlbmNvbnZlcnRlclxWMVxHUEJNZXRhZGF0YeoCG1N1bnJpc2U6OlRva2VuY29udmVydGVyOjpWMWIGcHJvdG8z", [file_amino_amino, file_cosmos_base_v1beta1_coin, file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gogoproto_gogo, file_sunrise_tokenconverter_v1_params]);

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * @generated from message sunrise.tokenconverter.v1.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"sunrise.tokenconverter.v1.MsgUpdateParams"> & {
  /**
   * authority is the address that controls the module (defaults to x/gov unless overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: sunrise.tokenconverter.v1.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message sunrise.tokenconverter.v1.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenconverter_v1_tx, 0);

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * @generated from message sunrise.tokenconverter.v1.MsgUpdateParamsResponse
 */
export type MsgUpdateParamsResponse = Message<"sunrise.tokenconverter.v1.MsgUpdateParamsResponse"> & {
};

/**
 * Describes the message sunrise.tokenconverter.v1.MsgUpdateParamsResponse.
 * Use `create(MsgUpdateParamsResponseSchema)` to create a new message.
 */
export const MsgUpdateParamsResponseSchema: GenMessage<MsgUpdateParamsResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenconverter_v1_tx, 1);

/**
 * MsgConvert
 *
 * @generated from message sunrise.tokenconverter.v1.MsgConvert
 */
export type MsgConvert = Message<"sunrise.tokenconverter.v1.MsgConvert"> & {
  /**
   * @generated from field: string sender = 1;
   */
  sender: string;

  /**
   * Amount of bond denom
   *
   * @generated from field: string amount = 2;
   */
  amount: string;
};

/**
 * Describes the message sunrise.tokenconverter.v1.MsgConvert.
 * Use `create(MsgConvertSchema)` to create a new message.
 */
export const MsgConvertSchema: GenMessage<MsgConvert> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenconverter_v1_tx, 2);

/**
 * MsgConvertResponse
 *
 * @generated from message sunrise.tokenconverter.v1.MsgConvertResponse
 */
export type MsgConvertResponse = Message<"sunrise.tokenconverter.v1.MsgConvertResponse"> & {
};

/**
 * Describes the message sunrise.tokenconverter.v1.MsgConvertResponse.
 * Use `create(MsgConvertResponseSchema)` to create a new message.
 */
export const MsgConvertResponseSchema: GenMessage<MsgConvertResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenconverter_v1_tx, 3);

/**
 * MsgSend
 *
 * @generated from message sunrise.tokenconverter.v1.MsgSend
 */
export type MsgSend = Message<"sunrise.tokenconverter.v1.MsgSend"> & {
  /**
   * @generated from field: string from_address = 1;
   */
  fromAddress: string;

  /**
   * @generated from field: string to_address = 2;
   */
  toAddress: string;

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin amount = 3;
   */
  amount: Coin[];
};

/**
 * Describes the message sunrise.tokenconverter.v1.MsgSend.
 * Use `create(MsgSendSchema)` to create a new message.
 */
export const MsgSendSchema: GenMessage<MsgSend> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenconverter_v1_tx, 4);

/**
 * MsgSendResponse
 *
 * @generated from message sunrise.tokenconverter.v1.MsgSendResponse
 */
export type MsgSendResponse = Message<"sunrise.tokenconverter.v1.MsgSendResponse"> & {
};

/**
 * Describes the message sunrise.tokenconverter.v1.MsgSendResponse.
 * Use `create(MsgSendResponseSchema)` to create a new message.
 */
export const MsgSendResponseSchema: GenMessage<MsgSendResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenconverter_v1_tx, 5);

/**
 * Msg defines the Msg service.
 *
 * @generated from service sunrise.tokenconverter.v1.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   *
   * @generated from rpc sunrise.tokenconverter.v1.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof MsgUpdateParamsResponseSchema;
  },
  /**
   * Convert
   *
   * @generated from rpc sunrise.tokenconverter.v1.Msg.Convert
   */
  convert: {
    methodKind: "unary";
    input: typeof MsgConvertSchema;
    output: typeof MsgConvertResponseSchema;
  },
  /**
   * Send
   *
   * @generated from rpc sunrise.tokenconverter.v1.Msg.Send
   */
  send: {
    methodKind: "unary";
    input: typeof MsgSendSchema;
    output: typeof MsgSendResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sunrise_tokenconverter_v1_tx, 0);

