// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/da/v0/params.proto (package sunrise.da.v0, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/da/v0/params.proto.
 */
export const file_sunrise_da_v0_params: GenFile = /*@__PURE__*/
  fileDesc("ChpzdW5yaXNlL2RhL3YwL3BhcmFtcy5wcm90bxINc3VucmlzZS5kYS52MCLSBgoGUGFyYW1zEhgKEHB1Ymxpc2hfZGF0YV9nYXMYASABKAQSKwoTY2hhbGxlbmdlX3RocmVzaG9sZBgCIAEoCUIO0rQtCmNvc21vcy5EZWMSKgoScmVwbGljYXRpb25fZmFjdG9yGAMgASgJQg7StC0KY29zbW9zLkRlYxITCgtzbGFzaF9lcG9jaBgEIAEoBBItChVzbGFzaF9mYXVsdF90aHJlc2hvbGQYBSABKAlCDtK0LQpjb3Ntb3MuRGVjEiYKDnNsYXNoX2ZyYWN0aW9uGAYgASgJQg7StC0KY29zbW9zLkRlYxI9ChBjaGFsbGVuZ2VfcGVyaW9kGAcgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uQgjI3h8AmN8fARI5Cgxwcm9vZl9wZXJpb2QYCCABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb25CCMjeHwCY3x8BEkQKF3JlamVjdGVkX3JlbW92YWxfcGVyaW9kGAkgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uQgjI3h8AmN8fARJEChd2ZXJpZmllZF9yZW1vdmFsX3BlcmlvZBgKIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbkIIyN4fAJjfHwESbAoXcHVibGlzaF9kYXRhX2NvbGxhdGVyYWwYCyADKAsyGS5jb3Ntb3MuYmFzZS52MWJldGExLkNvaW5CMMjeHwCq3x8oZ2l0aHViLmNvbS9jb3Ntb3MvY29zbW9zLXNkay90eXBlcy5Db2lucxJxChxzdWJtaXRfaW52YWxpZGl0eV9jb2xsYXRlcmFsGAwgAygLMhkuY29zbW9zLmJhc2UudjFiZXRhMS5Db2luQjDI3h8Aqt8fKGdpdGh1Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsvdHlwZXMuQ29pbnMSGQoRemtwX3ZlcmlmeWluZ19rZXkYDSABKAwSFwoPemtwX3Byb3Zpbmdfa2V5GA4gASgMEhcKD21pbl9zaGFyZF9jb3VudBgPIAEoBBIXCg9tYXhfc2hhcmRfY291bnQYECABKAQSFgoObWF4X3NoYXJkX3NpemUYESABKAQ6BOigHwFCogEKEWNvbS5zdW5yaXNlLmRhLnYwQgtQYXJhbXNQcm90b1ABWipnaXRodWIuY29tL3N1bnJpc2VsYXllci9zdW5yaXNlL3gvZGEvdHlwZXOiAgNTRFaqAg1TdW5yaXNlLkRhLlYwygINU3VucmlzZVxEYVxWMOICGVN1bnJpc2VcRGFcVjBcR1BCTWV0YWRhdGHqAg9TdW5yaXNlOjpEYTo6VjBiBnByb3RvMw", [file_cosmos_base_v1beta1_coin, file_cosmos_proto_cosmos, file_gogoproto_gogo, file_google_protobuf_duration]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message sunrise.da.v0.Params
 */
export type Params = Message<"sunrise.da.v0.Params"> & {
  /**
   * @generated from field: uint64 publish_data_gas = 1;
   */
  publishDataGas: bigint;

  /**
   * Invalid shard threshold required to go to STATUS_CHALLENGING.
   *
   * @generated from field: string challenge_threshold = 2;
   */
  challengeThreshold: string;

  /**
   * https://docs.sunriselayer.io/learn/sunrise/data-availability#the-condition-of-data-availability
   *
   * @generated from field: string replication_factor = 3;
   */
  replicationFactor: string;

  /**
   * How many blocks of slash are done every
   *
   * @generated from field: uint64 slash_epoch = 4;
   */
  slashEpoch: bigint;

  /**
   * (number of challenges a validator did not submit proof / number of all challenge) is over this threshold in an epoch
   * that validator will be slashed
   *
   * @generated from field: string slash_fault_threshold = 5;
   */
  slashFaultThreshold: string;

  /**
   * voting power deducted during slash
   *
   * @generated from field: string slash_fraction = 6;
   */
  slashFraction: string;

  /**
   * @generated from field: google.protobuf.Duration challenge_period = 7;
   */
  challengePeriod?: Duration;

  /**
   * @generated from field: google.protobuf.Duration proof_period = 8;
   */
  proofPeriod?: Duration;

  /**
   * @generated from field: google.protobuf.Duration rejected_removal_period = 9;
   */
  rejectedRemovalPeriod?: Duration;

  /**
   * @generated from field: google.protobuf.Duration verified_removal_period = 10;
   */
  verifiedRemovalPeriod?: Duration;

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin publish_data_collateral = 11;
   */
  publishDataCollateral: Coin[];

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin submit_invalidity_collateral = 12;
   */
  submitInvalidityCollateral: Coin[];

  /**
   * @generated from field: bytes zkp_verifying_key = 13;
   */
  zkpVerifyingKey: Uint8Array;

  /**
   * proving key used in sunrise-data
   *
   * @generated from field: bytes zkp_proving_key = 14;
   */
  zkpProvingKey: Uint8Array;

  /**
   * min_shard_count used in sunrise-data
   *
   * @generated from field: uint64 min_shard_count = 15;
   */
  minShardCount: bigint;

  /**
   * max_shard_count used in sunrise-data
   *
   * @generated from field: uint64 max_shard_count = 16;
   */
  maxShardCount: bigint;

  /**
   * max_shard_size used in sunrise-data
   *
   * @generated from field: uint64 max_shard_size = 17;
   */
  maxShardSize: bigint;
};

/**
 * Describes the message sunrise.da.v0.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_sunrise_da_v0_params, 0);

