// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/da/v0/published_data.proto (package sunrise.da.v0, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { Coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/da/v0/published_data.proto.
 */
export const file_sunrise_da_v0_published_data: GenFile = /*@__PURE__*/
  fileDesc("CiJzdW5yaXNlL2RhL3YwL3B1Ymxpc2hlZF9kYXRhLnByb3RvEg1zdW5yaXNlLmRhLnYwIuMECg1QdWJsaXNoZWREYXRhEhQKDG1ldGFkYXRhX3VyaRgBIAEoCRIhChJwYXJpdHlfc2hhcmRfY291bnQYAiABKARCBajnsCoBEhsKE3NoYXJkX2RvdWJsZV9oYXNoZXMYAyADKAwSNwoJdGltZXN0YW1wGAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIIyN4fAJDfHwESJQoGc3RhdHVzGAUgASgOMhUuc3VucmlzZS5kYS52MC5TdGF0dXMSEQoJcHVibGlzaGVyGAYgASgJEhIKCmNoYWxsZW5nZXIYByABKAkSbAoXcHVibGlzaF9kYXRhX2NvbGxhdGVyYWwYCCADKAsyGS5jb3Ntb3MuYmFzZS52MWJldGExLkNvaW5CMMjeHwCq3x8oZ2l0aHViLmNvbS9jb3Ntb3MvY29zbW9zLXNkay90eXBlcy5Db2lucxJxChxzdWJtaXRfaW52YWxpZGl0eV9jb2xsYXRlcmFsGAkgAygLMhkuY29zbW9zLmJhc2UudjFiZXRhMS5Db2luQjDI3h8Aqt8fKGdpdGh1Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsvdHlwZXMuQ29pbnMSQQoTcHVibGlzaGVkX3RpbWVzdGFtcBgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCCMjeHwCQ3x8BEhgKEGRhdGFfc291cmNlX2luZm8YCyABKAkSFwoPdmVyaWZpZWRfaGVpZ2h0GAwgASgDEh4KFmNoYWxsZW5naW5nX3ZhbGlkYXRvcnMYDSADKAkiTgoFUHJvb2YSFAoMbWV0YWRhdGFfdXJpGAEgASgJEg4KBnNlbmRlchgCIAEoCRIPCgdpbmRpY2VzGAMgAygDEg4KBnByb29mcxgEIAMoDCJDCgpJbnZhbGlkaXR5EhQKDG1ldGFkYXRhX3VyaRgBIAEoCRIOCgZzZW5kZXIYAiABKAkSDwoHaW5kaWNlcxgDIAMoAyp/CgZTdGF0dXMSFgoSU1RBVFVTX1VOU1BFQ0lGSUVEEAASEwoPU1RBVFVTX1ZFUklGSUVEEAESEwoPU1RBVFVTX1JFSkVDVEVEEAISGwoXU1RBVFVTX0NIQUxMRU5HRV9QRVJJT0QQAxIWChJTVEFUVVNfQ0hBTExFTkdJTkcQBEKpAQoRY29tLnN1bnJpc2UuZGEudjBCElB1Ymxpc2hlZERhdGFQcm90b1ABWipnaXRodWIuY29tL3N1bnJpc2VsYXllci9zdW5yaXNlL3gvZGEvdHlwZXOiAgNTRFaqAg1TdW5yaXNlLkRhLlYwygINU3VucmlzZVxEYVxWMOICGVN1bnJpc2VcRGFcVjBcR1BCTWV0YWRhdGHqAg9TdW5yaXNlOjpEYTo6VjBiBnByb3RvMw", [file_amino_amino, file_cosmos_base_v1beta1_coin, file_gogoproto_gogo, file_google_protobuf_timestamp]);

/**
 * PublishedData
 *
 * @generated from message sunrise.da.v0.PublishedData
 */
export type PublishedData = Message<"sunrise.da.v0.PublishedData"> & {
  /**
   * @generated from field: string metadata_uri = 1;
   */
  metadataUri: string;

  /**
   * @generated from field: uint64 parity_shard_count = 2;
   */
  parityShardCount: bigint;

  /**
   * @generated from field: repeated bytes shard_double_hashes = 3;
   */
  shardDoubleHashes: Uint8Array[];

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: sunrise.da.v0.Status status = 5;
   */
  status: Status;

  /**
   * @generated from field: string publisher = 6;
   */
  publisher: string;

  /**
   * @generated from field: string challenger = 7;
   */
  challenger: string;

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin publish_data_collateral = 8;
   */
  publishDataCollateral: Coin[];

  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin submit_invalidity_collateral = 9;
   */
  submitInvalidityCollateral: Coin[];

  /**
   * @generated from field: google.protobuf.Timestamp published_timestamp = 10;
   */
  publishedTimestamp?: Timestamp;

  /**
   * @generated from field: string data_source_info = 11;
   */
  dataSourceInfo: string;

  /**
   * @generated from field: int64 verified_height = 12;
   */
  verifiedHeight: bigint;

  /**
   * challenger_validators is the list of validators that were active when the data was challenging.
   *
   * @generated from field: repeated string challenging_validators = 13;
   */
  challengingValidators: string[];
};

/**
 * Describes the message sunrise.da.v0.PublishedData.
 * Use `create(PublishedDataSchema)` to create a new message.
 */
export const PublishedDataSchema: GenMessage<PublishedData> = /*@__PURE__*/
  messageDesc(file_sunrise_da_v0_published_data, 0);

/**
 * Proof
 *
 * @generated from message sunrise.da.v0.Proof
 */
export type Proof = Message<"sunrise.da.v0.Proof"> & {
  /**
   * @generated from field: string metadata_uri = 1;
   */
  metadataUri: string;

  /**
   * @generated from field: string sender = 2;
   */
  sender: string;

  /**
   * @generated from field: repeated int64 indices = 3;
   */
  indices: bigint[];

  /**
   * @generated from field: repeated bytes proofs = 4;
   */
  proofs: Uint8Array[];
};

/**
 * Describes the message sunrise.da.v0.Proof.
 * Use `create(ProofSchema)` to create a new message.
 */
export const ProofSchema: GenMessage<Proof> = /*@__PURE__*/
  messageDesc(file_sunrise_da_v0_published_data, 1);

/**
 * Invalidity
 *
 * @generated from message sunrise.da.v0.Invalidity
 */
export type Invalidity = Message<"sunrise.da.v0.Invalidity"> & {
  /**
   * @generated from field: string metadata_uri = 1;
   */
  metadataUri: string;

  /**
   * @generated from field: string sender = 2;
   */
  sender: string;

  /**
   * @generated from field: repeated int64 indices = 3;
   */
  indices: bigint[];
};

/**
 * Describes the message sunrise.da.v0.Invalidity.
 * Use `create(InvaliditySchema)` to create a new message.
 */
export const InvaliditySchema: GenMessage<Invalidity> = /*@__PURE__*/
  messageDesc(file_sunrise_da_v0_published_data, 2);

/**
 * PublishedDataStatus
 *
 * @generated from enum sunrise.da.v0.Status
 */
export enum Status {
  /**
   * Default value
   *
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Verified
   *
   * @generated from enum value: STATUS_VERIFIED = 1;
   */
  VERIFIED = 1,

  /**
   * Rejected
   *
   * @generated from enum value: STATUS_REJECTED = 2;
   */
  REJECTED = 2,

  /**
   * Verified the votes from the validators. Challenge can be received (after preBlocker)
   *
   * @generated from enum value: STATUS_CHALLENGE_PERIOD = 3;
   */
  CHALLENGE_PERIOD = 3,

  /**
   * A certain number of SubmitInvalidity received. Validators can send SubmitValidityProof tx.
   *
   * @generated from enum value: STATUS_CHALLENGING = 4;
   */
  CHALLENGING = 4,
}

/**
 * Describes the enum sunrise.da.v0.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_sunrise_da_v0_published_data, 0);

