// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/tokenfactory/v1/authorityMetadata.proto (package sunrise.tokenfactory.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/tokenfactory/v1/authorityMetadata.proto.
 */
export const file_sunrise_tokenfactory_v1_authorityMetadata: GenFile = /*@__PURE__*/
  fileDesc("Ci9zdW5yaXNlL3Rva2VuZmFjdG9yeS92MS9hdXRob3JpdHlNZXRhZGF0YS5wcm90bxIXc3VucmlzZS50b2tlbmZhY3RvcnkudjEiPwoWRGVub21BdXRob3JpdHlNZXRhZGF0YRIfCgVhZG1pbhgBIAEoCUIQ8t4fDHlhbWw6ImFkbWluIjoE6KAfAULpAQobY29tLnN1bnJpc2UudG9rZW5mYWN0b3J5LnYxQhZBdXRob3JpdHlNZXRhZGF0YVByb3RvUAFaNGdpdGh1Yi5jb20vc3VucmlzZWxheWVyL3N1bnJpc2UveC90b2tlbmZhY3RvcnkvdHlwZXOiAgNTVFiqAhdTdW5yaXNlLlRva2VuZmFjdG9yeS5WMcoCF1N1bnJpc2VcVG9rZW5mYWN0b3J5XFYx4gIjU3VucmlzZVxUb2tlbmZhY3RvcnlcVjFcR1BCTWV0YWRhdGHqAhlTdW5yaXNlOjpUb2tlbmZhY3Rvcnk6OlYxYgZwcm90bzM", [file_gogoproto_gogo]);

/**
 * DenomAuthorityMetadata specifies metadata for addresses that have specific
 * capabilities over a token factory denom. Right now there is only one Admin
 * permission, but is planned to be extended to the future.
 *
 * @generated from message sunrise.tokenfactory.v1.DenomAuthorityMetadata
 */
export type DenomAuthorityMetadata = Message<"sunrise.tokenfactory.v1.DenomAuthorityMetadata"> & {
  /**
   * Can be empty for no admin, or a valid osmosis address
   *
   * @generated from field: string admin = 1;
   */
  admin: string;
};

/**
 * Describes the message sunrise.tokenfactory.v1.DenomAuthorityMetadata.
 * Use `create(DenomAuthorityMetadataSchema)` to create a new message.
 */
export const DenomAuthorityMetadataSchema: GenMessage<DenomAuthorityMetadata> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenfactory_v1_authorityMetadata, 0);

