// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/tokenfactory/v1/params.proto (package sunrise.tokenfactory.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../amino/amino_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Coin } from "../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../cosmos/base/v1beta1/coin_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/tokenfactory/v1/params.proto.
 */
export const file_sunrise_tokenfactory_v1_params: GenFile = /*@__PURE__*/
  fileDesc("CiRzdW5yaXNlL3Rva2VuZmFjdG9yeS92MS9wYXJhbXMucHJvdG8SF3N1bnJpc2UudG9rZW5mYWN0b3J5LnYxIv8BCgZQYXJhbXMShAEKEmRlbm9tX2NyZWF0aW9uX2ZlZRgBIAMoCzIZLmNvc21vcy5iYXNlLnYxYmV0YTEuQ29pbkJNyN4fAPLeHxl5YW1sOiJkZW5vbV9jcmVhdGlvbl9mZWUiqt8fKGdpdGh1Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsvdHlwZXMuQ29pbnMSTQoaZGVub21fY3JlYXRpb25fZ2FzX2NvbnN1bWUYAiABKARCKcjeHwHy3h8heWFtbDoiZGVub21fY3JlYXRpb25fZ2FzX2NvbnN1bWUiOh/ooB8BiuewKhZzdW5yaXNlL2ZhY3RvcnkvUGFyYW1zQt4BChtjb20uc3VucmlzZS50b2tlbmZhY3RvcnkudjFCC1BhcmFtc1Byb3RvUAFaNGdpdGh1Yi5jb20vc3VucmlzZWxheWVyL3N1bnJpc2UveC90b2tlbmZhY3RvcnkvdHlwZXOiAgNTVFiqAhdTdW5yaXNlLlRva2VuZmFjdG9yeS5WMcoCF1N1bnJpc2VcVG9rZW5mYWN0b3J5XFYx4gIjU3VucmlzZVxUb2tlbmZhY3RvcnlcVjFcR1BCTWV0YWRhdGHqAhlTdW5yaXNlOjpUb2tlbmZhY3Rvcnk6OlYxYgZwcm90bzM", [file_amino_amino, file_gogoproto_gogo, file_cosmos_base_v1beta1_coin]);

/**
 * Params defines the parameters for the tokenfactory module.
 *
 * @generated from message sunrise.tokenfactory.v1.Params
 */
export type Params = Message<"sunrise.tokenfactory.v1.Params"> & {
  /**
   * DenomCreationFee defines the fee to be charged on the creation of a new
   * denom. The fee is drawn from the MsgCreateDenom's sender account, and
   * transferred to the community pool.
   *
   * @generated from field: repeated cosmos.base.v1beta1.Coin denom_creation_fee = 1;
   */
  denomCreationFee: Coin[];

  /**
   * DenomCreationGasConsume defines the gas cost for creating a new denom.
   * This is intended as a spam deterrence mechanism.
   *
   * See: https://github.com/CosmWasm/token-factory/issues/11
   *
   * @generated from field: uint64 denom_creation_gas_consume = 2;
   */
  denomCreationGasConsume: bigint;
};

/**
 * Describes the message sunrise.tokenfactory.v1.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_sunrise_tokenfactory_v1_params, 0);

