// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/cron/v1/query.proto (package sunrise.cron.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../amino/amino_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination_pb";
import { file_cosmos_base_query_v1beta1_pagination } from "../../../cosmos/base/query/v1beta1/pagination_pb";
import type { Params } from "./params_pb";
import { file_sunrise_cron_v1_params } from "./params_pb";
import type { Schedule } from "./schedule_pb";
import { file_sunrise_cron_v1_schedule } from "./schedule_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/cron/v1/query.proto.
 */
export const file_sunrise_cron_v1_query: GenFile = /*@__PURE__*/
  fileDesc("ChtzdW5yaXNlL2Nyb24vdjEvcXVlcnkucHJvdG8SD3N1bnJpc2UuY3Jvbi52MSIUChJRdWVyeVBhcmFtc1JlcXVlc3QiSQoTUXVlcnlQYXJhbXNSZXNwb25zZRIyCgZwYXJhbXMYASABKAsyFy5zdW5yaXNlLmNyb24udjEuUGFyYW1zQgnI3h8AqOewKgEiJwoXUXVlcnlHZXRTY2hlZHVsZVJlcXVlc3QSDAoEbmFtZRgBIAEoCSJNChhRdWVyeUdldFNjaGVkdWxlUmVzcG9uc2USMQoIc2NoZWR1bGUYASABKAsyGS5zdW5yaXNlLmNyb24udjEuU2NoZWR1bGVCBMjeHwAiUwoVUXVlcnlTY2hlZHVsZXNSZXF1ZXN0EjoKCnBhZ2luYXRpb24YASABKAsyJi5jb3Ntb3MuYmFzZS5xdWVyeS52MWJldGExLlBhZ2VSZXF1ZXN0IokBChZRdWVyeVNjaGVkdWxlc1Jlc3BvbnNlEjIKCXNjaGVkdWxlcxgBIAMoCzIZLnN1bnJpc2UuY3Jvbi52MS5TY2hlZHVsZUIEyN4fABI7CgpwYWdpbmF0aW9uGAIgASgLMicuY29zbW9zLmJhc2UucXVlcnkudjFiZXRhMS5QYWdlUmVzcG9uc2UymAMKBVF1ZXJ5EoEBCgZQYXJhbXMSIy5zdW5yaXNlLmNyb24udjEuUXVlcnlQYXJhbXNSZXF1ZXN0GiQuc3VucmlzZS5jcm9uLnYxLlF1ZXJ5UGFyYW1zUmVzcG9uc2UiLILT5JMCJhIkL3N1bnJpc2VsYXllci9zdW5yaXNlL2Nyb24vdjEvcGFyYW1zEokBCghTY2hlZHVsZRIoLnN1bnJpc2UuY3Jvbi52MS5RdWVyeUdldFNjaGVkdWxlUmVxdWVzdBopLnN1bnJpc2UuY3Jvbi52MS5RdWVyeUdldFNjaGVkdWxlUmVzcG9uc2UiKILT5JMCIhIgL3N1bnJpc2UvY3Jvbi92MS9zY2hlZHVsZS97bmFtZX0SfwoJU2NoZWR1bGVzEiYuc3VucmlzZS5jcm9uLnYxLlF1ZXJ5U2NoZWR1bGVzUmVxdWVzdBonLnN1bnJpc2UuY3Jvbi52MS5RdWVyeVNjaGVkdWxlc1Jlc3BvbnNlIiGC0+STAhsSGS9zdW5yaXNlL2Nyb24vdjEvc2NoZWR1bGVCrQEKE2NvbS5zdW5yaXNlLmNyb24udjFCClF1ZXJ5UHJvdG9QAVosZ2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L2Nyb24vdHlwZXOiAgNTQ1iqAg9TdW5yaXNlLkNyb24uVjHKAg9TdW5yaXNlXENyb25cVjHiAhtTdW5yaXNlXENyb25cVjFcR1BCTWV0YWRhdGHqAhFTdW5yaXNlOjpDcm9uOjpWMWIGcHJvdG8z", [file_amino_amino, file_gogoproto_gogo, file_google_api_annotations, file_cosmos_base_query_v1beta1_pagination, file_sunrise_cron_v1_params, file_sunrise_cron_v1_schedule]);

/**
 * QueryParamsRequest is request type for the Query/Params RPC method.
 *
 * @generated from message sunrise.cron.v1.QueryParamsRequest
 */
export type QueryParamsRequest = Message<"sunrise.cron.v1.QueryParamsRequest"> & {
};

/**
 * Describes the message sunrise.cron.v1.QueryParamsRequest.
 * Use `create(QueryParamsRequestSchema)` to create a new message.
 */
export const QueryParamsRequestSchema: GenMessage<QueryParamsRequest> = /*@__PURE__*/
  messageDesc(file_sunrise_cron_v1_query, 0);

/**
 * QueryParamsResponse is response type for the Query/Params RPC method.
 *
 * @generated from message sunrise.cron.v1.QueryParamsResponse
 */
export type QueryParamsResponse = Message<"sunrise.cron.v1.QueryParamsResponse"> & {
  /**
   * params holds all the parameters of this module.
   *
   * @generated from field: sunrise.cron.v1.Params params = 1;
   */
  params?: Params;
};

/**
 * Describes the message sunrise.cron.v1.QueryParamsResponse.
 * Use `create(QueryParamsResponseSchema)` to create a new message.
 */
export const QueryParamsResponseSchema: GenMessage<QueryParamsResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_cron_v1_query, 1);

/**
 * The request type for the Query/Schedule RPC method.
 *
 * @generated from message sunrise.cron.v1.QueryGetScheduleRequest
 */
export type QueryGetScheduleRequest = Message<"sunrise.cron.v1.QueryGetScheduleRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message sunrise.cron.v1.QueryGetScheduleRequest.
 * Use `create(QueryGetScheduleRequestSchema)` to create a new message.
 */
export const QueryGetScheduleRequestSchema: GenMessage<QueryGetScheduleRequest> = /*@__PURE__*/
  messageDesc(file_sunrise_cron_v1_query, 2);

/**
 * The response type for the Query/Params RPC method.
 *
 * @generated from message sunrise.cron.v1.QueryGetScheduleResponse
 */
export type QueryGetScheduleResponse = Message<"sunrise.cron.v1.QueryGetScheduleResponse"> & {
  /**
   * @generated from field: sunrise.cron.v1.Schedule schedule = 1;
   */
  schedule?: Schedule;
};

/**
 * Describes the message sunrise.cron.v1.QueryGetScheduleResponse.
 * Use `create(QueryGetScheduleResponseSchema)` to create a new message.
 */
export const QueryGetScheduleResponseSchema: GenMessage<QueryGetScheduleResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_cron_v1_query, 3);

/**
 * The request type for the Query/Schedules RPC method.
 *
 * @generated from message sunrise.cron.v1.QuerySchedulesRequest
 */
export type QuerySchedulesRequest = Message<"sunrise.cron.v1.QuerySchedulesRequest"> & {
  /**
   * @generated from field: cosmos.base.query.v1beta1.PageRequest pagination = 1;
   */
  pagination?: PageRequest;
};

/**
 * Describes the message sunrise.cron.v1.QuerySchedulesRequest.
 * Use `create(QuerySchedulesRequestSchema)` to create a new message.
 */
export const QuerySchedulesRequestSchema: GenMessage<QuerySchedulesRequest> = /*@__PURE__*/
  messageDesc(file_sunrise_cron_v1_query, 4);

/**
 * The response type for the Query/Params RPC method.
 *
 * @generated from message sunrise.cron.v1.QuerySchedulesResponse
 */
export type QuerySchedulesResponse = Message<"sunrise.cron.v1.QuerySchedulesResponse"> & {
  /**
   * @generated from field: repeated sunrise.cron.v1.Schedule schedules = 1;
   */
  schedules: Schedule[];

  /**
   * @generated from field: cosmos.base.query.v1beta1.PageResponse pagination = 2;
   */
  pagination?: PageResponse;
};

/**
 * Describes the message sunrise.cron.v1.QuerySchedulesResponse.
 * Use `create(QuerySchedulesResponseSchema)` to create a new message.
 */
export const QuerySchedulesResponseSchema: GenMessage<QuerySchedulesResponse> = /*@__PURE__*/
  messageDesc(file_sunrise_cron_v1_query, 5);

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service sunrise.cron.v1.Query
 */
export const Query: GenService<{
  /**
   * Parameters queries the parameters of the module.
   *
   * @generated from rpc sunrise.cron.v1.Query.Params
   */
  params: {
    methodKind: "unary";
    input: typeof QueryParamsRequestSchema;
    output: typeof QueryParamsResponseSchema;
  },
  /**
   * Queries a Schedule by name.
   *
   * @generated from rpc sunrise.cron.v1.Query.Schedule
   */
  schedule: {
    methodKind: "unary";
    input: typeof QueryGetScheduleRequestSchema;
    output: typeof QueryGetScheduleResponseSchema;
  },
  /**
   * Queries a list of Schedule items.
   *
   * @generated from rpc sunrise.cron.v1.Query.Schedules
   */
  schedules: {
    methodKind: "unary";
    input: typeof QuerySchedulesRequestSchema;
    output: typeof QuerySchedulesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_sunrise_cron_v1_query, 0);

