// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/fee/v1/params.proto (package sunrise.fee.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/fee/v1/params.proto.
 */
export const file_sunrise_fee_v1_params: GenFile = /*@__PURE__*/
  fileDesc("ChtzdW5yaXNlL2ZlZS92MS9wYXJhbXMucHJvdG8SDnN1bnJpc2UuZmVlLnYxIpwBCgZQYXJhbXMSEQoJZmVlX2Rlbm9tGAEgASgJEhIKCmJ1cm5fZGVub20YAiABKAkSIgoKYnVybl9yYXRpbxgDIAEoCUIO0rQtCmNvc21vcy5EZWMSFAoMYnVybl9wb29sX2lkGAQgASgEEhQKDGJ1cm5fZW5hYmxlZBgFIAEoCDob6KAfAYrnsCoSc3VucmlzZS9mZWUvUGFyYW1zQqgBChJjb20uc3VucmlzZS5mZWUudjFCC1BhcmFtc1Byb3RvUAFaK2dpdGh1Yi5jb20vc3VucmlzZWxheWVyL3N1bnJpc2UveC9mZWUvdHlwZXOiAgNTRliqAg5TdW5yaXNlLkZlZS5WMcoCDlN1bnJpc2VcRmVlXFYx4gIaU3VucmlzZVxGZWVcVjFcR1BCTWV0YWRhdGHqAhBTdW5yaXNlOjpGZWU6OlYxYgZwcm90bzM", [file_cosmos_proto_cosmos, file_gogoproto_gogo, file_amino_amino]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message sunrise.fee.v1.Params
 */
export type Params = Message<"sunrise.fee.v1.Params"> & {
  /**
   * @generated from field: string fee_denom = 1;
   */
  feeDenom: string;

  /**
   * @generated from field: string burn_denom = 2;
   */
  burnDenom: string;

  /**
   * @generated from field: string burn_ratio = 3;
   */
  burnRatio: string;

  /**
   * @generated from field: uint64 burn_pool_id = 4;
   */
  burnPoolId: bigint;

  /**
   * @generated from field: bool burn_enabled = 5;
   */
  burnEnabled: boolean;
};

/**
 * Describes the message sunrise.fee.v1.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_sunrise_fee_v1_params, 0);

