// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/stable/v1/params.proto (package sunrise.stable.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../amino/amino_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/stable/v1/params.proto.
 */
export const file_sunrise_stable_v1_params: GenFile = /*@__PURE__*/
  fileDesc("Ch5zdW5yaXNlL3N0YWJsZS92MS9wYXJhbXMucHJvdG8SEXN1bnJpc2Uuc3RhYmxlLnYxIlkKBlBhcmFtcxIUCgxzdGFibGVfZGVub20YASABKAkSGQoRYWxsb3dlZF9hZGRyZXNzZXMYAiADKAk6HuigHwGK57AqFXN1bnJpc2Uvc3RhYmxlL1BhcmFtc0K6AQoVY29tLnN1bnJpc2Uuc3RhYmxlLnYxQgtQYXJhbXNQcm90b1ABWi5naXRodWIuY29tL3N1bnJpc2VsYXllci9zdW5yaXNlL3gvc3RhYmxlL3R5cGVzogIDU1NYqgIRU3VucmlzZS5TdGFibGUuVjHKAhFTdW5yaXNlXFN0YWJsZVxWMeICHVN1bnJpc2VcU3RhYmxlXFYxXEdQQk1ldGFkYXRh6gITU3VucmlzZTo6U3RhYmxlOjpWMWIGcHJvdG8z", [file_amino_amino, file_gogoproto_gogo]);

/**
 * Params defines the parameters for the module.
 *
 * @generated from message sunrise.stable.v1.Params
 */
export type Params = Message<"sunrise.stable.v1.Params"> & {
  /**
   * @generated from field: string stable_denom = 1;
   */
  stableDenom: string;

  /**
   * @generated from field: repeated string allowed_addresses = 2;
   */
  allowedAddresses: string[];
};

/**
 * Describes the message sunrise.stable.v1.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_sunrise_stable_v1_params, 0);

