// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file cometbft/version/v1/types.proto (package cometbft.version.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cometbft/version/v1/types.proto.
 */
export const file_cometbft_version_v1_types: GenFile = /*@__PURE__*/
  fileDesc("Ch9jb21ldGJmdC92ZXJzaW9uL3YxL3R5cGVzLnByb3RvEhNjb21ldGJmdC52ZXJzaW9uLnYxIikKA0FwcBIQCghwcm90b2NvbBgBIAEoBBIQCghzb2Z0d2FyZRgCIAEoCSItCglDb25zZW5zdXMSDQoFYmxvY2sYASABKAQSCwoDYXBwGAIgASgEOgTooB8BQskBChdjb20uY29tZXRiZnQudmVyc2lvbi52MUIKVHlwZXNQcm90b1ABWjRnaXRodWIuY29tL2NvbWV0YmZ0L2NvbWV0YmZ0L2FwaS9jb21ldGJmdC92ZXJzaW9uL3YxogIDQ1ZYqgITQ29tZXRiZnQuVmVyc2lvbi5WMcoCE0NvbWV0YmZ0XFZlcnNpb25cVjHiAh9Db21ldGJmdFxWZXJzaW9uXFYxXEdQQk1ldGFkYXRh6gIVQ29tZXRiZnQ6OlZlcnNpb246OlYxYgZwcm90bzM", [file_gogoproto_gogo]);

/**
 * App includes the protocol and software version for the application.
 * This information is included in ResponseInfo. The App.Protocol can be
 * updated in ResponseEndBlock.
 *
 * @generated from message cometbft.version.v1.App
 */
export type App = Message<"cometbft.version.v1.App"> & {
  /**
   * @generated from field: uint64 protocol = 1;
   */
  protocol: bigint;

  /**
   * @generated from field: string software = 2;
   */
  software: string;
};

/**
 * Describes the message cometbft.version.v1.App.
 * Use `create(AppSchema)` to create a new message.
 */
export const AppSchema: GenMessage<App> = /*@__PURE__*/
  messageDesc(file_cometbft_version_v1_types, 0);

/**
 * Consensus captures the consensus rules for processing a block in the blockchain,
 * including all blockchain data structures and the rules of the application's
 * state transition machine.
 *
 * @generated from message cometbft.version.v1.Consensus
 */
export type Consensus = Message<"cometbft.version.v1.Consensus"> & {
  /**
   * @generated from field: uint64 block = 1;
   */
  block: bigint;

  /**
   * @generated from field: uint64 app = 2;
   */
  app: bigint;
};

/**
 * Describes the message cometbft.version.v1.Consensus.
 * Use `create(ConsensusSchema)` to create a new message.
 */
export const ConsensusSchema: GenMessage<Consensus> = /*@__PURE__*/
  messageDesc(file_cometbft_version_v1_types, 1);

