// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file sunrise/lockup/v1/lockup_account.proto (package sunrise.lockup.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sunrise/lockup/v1/lockup_account.proto.
 */
export const file_sunrise_lockup_v1_lockup_account: GenFile = /*@__PURE__*/
  fileDesc("CiZzdW5yaXNlL2xvY2t1cC92MS9sb2NrdXBfYWNjb3VudC5wcm90bxIRc3VucmlzZS5sb2NrdXAudjEi7wMKDUxvY2t1cEFjY291bnQSKQoHYWRkcmVzcxgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEicKBW93bmVyGAIgASgJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmcSCgoCaWQYAyABKAQSEgoKc3RhcnRfdGltZRgEIAEoAxIQCghlbmRfdGltZRgFIAEoAxJFChBvcmlnaW5hbF9sb2NraW5nGAYgASgJQivI3h8A2t4fFWNvc21vc3Nkay5pby9tYXRoLkludNK0LQpjb3Ntb3MuSW50EkMKDmRlbGVnYXRlZF9mcmVlGAcgASgJQivI3h8A2t4fFWNvc21vc3Nkay5pby9tYXRoLkludNK0LQpjb3Ntb3MuSW50EkYKEWRlbGVnYXRlZF9sb2NraW5nGAggASgJQivI3h8A2t4fFWNvc21vc3Nkay5pby9tYXRoLkludNK0LQpjb3Ntb3MuSW50EjsKDnVuYm9uZF9lbnRyaWVzGAkgASgLMiMuc3VucmlzZS5sb2NrdXAudjEuVW5ib25kaW5nRW50cmllcxJHChJhZGRpdGlvbmFsX2xvY2tpbmcYCiABKAlCK8jeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW500rQtCmNvc21vcy5JbnQiRgoQVW5ib25kaW5nRW50cmllcxIyCgdlbnRyaWVzGAEgAygLMiEuc3VucmlzZS5sb2NrdXAudjEuVW5ib25kaW5nRW50cnkitgEKDlVuYm9uZGluZ0VudHJ5EhcKD2NyZWF0aW9uX2hlaWdodBgBIAEoAxIQCghlbmRfdGltZRgCIAEoAxI7CgZhbW91bnQYAyABKAlCK8jeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW500rQtCmNvc21vcy5JbnQSPAoRdmFsaWRhdG9yX2FkZHJlc3MYBCABKAlCIdK0LR1jb3Ntb3MuVmFsaWRhdG9yQWRkcmVzc1N0cmluZ0LBAQoVY29tLnN1bnJpc2UubG9ja3VwLnYxQhJMb2NrdXBBY2NvdW50UHJvdG9QAVouZ2l0aHViLmNvbS9zdW5yaXNlbGF5ZXIvc3VucmlzZS94L2xvY2t1cC90eXBlc6ICA1NMWKoCEVN1bnJpc2UuTG9ja3VwLlYxygIRU3VucmlzZVxMb2NrdXBcVjHiAh1TdW5yaXNlXExvY2t1cFxWMVxHUEJNZXRhZGF0YeoCE1N1bnJpc2U6OkxvY2t1cDo6VjFiBnByb3RvMw", [file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * LockupAccount defines the lockup account.
 *
 * @generated from message sunrise.lockup.v1.LockupAccount
 */
export type LockupAccount = Message<"sunrise.lockup.v1.LockupAccount"> & {
  /**
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * @generated from field: string owner = 2;
   */
  owner: string;

  /**
   * @generated from field: uint64 id = 3;
   */
  id: bigint;

  /**
   * @generated from field: int64 start_time = 4;
   */
  startTime: bigint;

  /**
   * @generated from field: int64 end_time = 5;
   */
  endTime: bigint;

  /**
   * @generated from field: string original_locking = 6;
   */
  originalLocking: string;

  /**
   * @generated from field: string delegated_free = 7;
   */
  delegatedFree: string;

  /**
   * @generated from field: string delegated_locking = 8;
   */
  delegatedLocking: string;

  /**
   * @generated from field: sunrise.lockup.v1.UnbondingEntries unbond_entries = 9;
   */
  unbondEntries?: UnbondingEntries;

  /**
   * @generated from field: string additional_locking = 10;
   */
  additionalLocking: string;
};

/**
 * Describes the message sunrise.lockup.v1.LockupAccount.
 * Use `create(LockupAccountSchema)` to create a new message.
 */
export const LockupAccountSchema: GenMessage<LockupAccount> = /*@__PURE__*/
  messageDesc(file_sunrise_lockup_v1_lockup_account, 0);

/**
 * UnbondingEntries list of elements
 *
 * @generated from message sunrise.lockup.v1.UnbondingEntries
 */
export type UnbondingEntries = Message<"sunrise.lockup.v1.UnbondingEntries"> & {
  /**
   * @generated from field: repeated sunrise.lockup.v1.UnbondingEntry entries = 1;
   */
  entries: UnbondingEntry[];
};

/**
 * Describes the message sunrise.lockup.v1.UnbondingEntries.
 * Use `create(UnbondingEntriesSchema)` to create a new message.
 */
export const UnbondingEntriesSchema: GenMessage<UnbondingEntries> = /*@__PURE__*/
  messageDesc(file_sunrise_lockup_v1_lockup_account, 1);

/**
 * UnbondingEntry defines an entry tracking the lockup account unbonding operation.
 *
 * @generated from message sunrise.lockup.v1.UnbondingEntry
 */
export type UnbondingEntry = Message<"sunrise.lockup.v1.UnbondingEntry"> & {
  /**
   * @generated from field: int64 creation_height = 1;
   */
  creationHeight: bigint;

  /**
   * end time of entry
   *
   * @generated from field: int64 end_time = 2;
   */
  endTime: bigint;

  /**
   * unbond amount
   *
   * @generated from field: string amount = 3;
   */
  amount: string;

  /**
   * validator address
   *
   * @generated from field: string validator_address = 4;
   */
  validatorAddress: string;
};

/**
 * Describes the message sunrise.lockup.v1.UnbondingEntry.
 * Use `create(UnbondingEntrySchema)` to create a new message.
 */
export const UnbondingEntrySchema: GenMessage<UnbondingEntry> = /*@__PURE__*/
  messageDesc(file_sunrise_lockup_v1_lockup_account, 2);

